[package]
name = "circuit"
compiler_version = ">=0.25.0"
type = "contract"

# Nargo.toml
[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="alpha-testnet", directory="noir-projects/aztec-nr/aztec" }